# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: 'arn:aws:iam::088198150793:role/karimo94-oidc-role' #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      
      # Setup Node in the CI/CD runner
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Setup AWS CDK and install Node dependecies
        run: |
          npm install -g aws-cdk

      - name: Deploy to AWS (CDK Deploy)
        run: cd ./bin && cdk deploy --require-approval never CdkStuffStack
      
      - name: CDK Synth
        run: cd ./bin && npx cdk synth

# build scripts in package.json

# "build": "cd ./infrastructure && npm run build"
# "test": "cd ./infrastructure/test && npm test"
# "cdk": "cd ./infrastructure && npx cdk"
# "synth": "cd ./infrastructure && npx cdk synth",
# "deploy:[env]": cd ./infrastructure && npx cdk deploy --require-approval never [name of your stage]